### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by rst-roomle** [github/gh-actions-importer#104]
I tried to install the extension using the command:
```
gh extension install github/gh-actions-importer
```
and received the response:
```
gh-actions-importer unsupported for darwin-arm64.
```
Have you planned to support `darwin-arm64` in the near future?

**Comment by j-dunham** [comment]
Hi @rst-roomle,

Sorry you are having this issue. Could you please do the following to help resolve this:
- provide your `gh` CLI version by running `gh version`
- upgrade the `gh` CLI, see the [docs](https://github.com/cli/cli#macos) for the correct command for the installation type you originally installed with.  
- retry installing the extension with `gh extension install github/gh-actions-importer`

**Comment by rst-roomle** [comment]
Hi @j-dunham,

`gh version`
returns: 
`gh version 2.27.0 (2023-04-07)`

upgrade using homebrew `brew upgrade gh`
returns: 
`Warning: gh 2.27.0 already installed`

`gh extension install github/gh-actions-importer`
returns:
`gh-actions-importer unsupported for darwin-arm64. Open an issue: gh issue create -R github/gh-actions-importer -t'Support darwin-arm64'`

Nothing changed so far.
Thank you for your feedback!

**Comment by j-dunham** [comment]
@rst-roomle thanks for the information!  Could you run `uname -ms` to verify that your system is indeed `darwin-arm64` and provide the output?  I am asking these questions because `gh-actions-importer` should work on that architecture and I am trying to figure out what maybe be different about your system

**Comment by rst-roomle** [comment]
@j-dunham when I execute 
`uname -ms` 
the result is 
`Darwin arm64`

I am using a MacBook Pro M1 no rosetta installed - if this might help somehow.

**Comment by rst-roomle** [comment]
Hi @j-dunham,
When I ran the command `gh extension install github/gh-actions-importer --pin v1.2.2` it took a few minutes until the installation finished.

The output was:
```
✓ Installed extension github/gh-actions-importer
✓ Pinned extension at v1.2.2
```

Executing the test command: 
```
gh actions-importer update && gh actions-importer version
```
returned 
```
Updating ghcr.io/actions-importer/cli:latest...
ghcr.io/actions-importer/cli:latest up-to-date
gh version 2.27.0 (2023-04-07)
gh actions-importer	github/gh-actions-importer	v1.2.2
actions-importer/cli:latest	v1.2.18380
```

Thanks a lot for the great solution!
