### ISSUE TITLE
Auditing fails for some projects

### ISSUE THREAD

**Issue by FabianBigler** [github/gh-actions-importer#124]
When I execute the following command: 
`gh actions-importer audit azure-devops -o output/azure_devops`
some of our projects may be migrated, but the others failed.

For the others we retrieve the following error:
There was an error extracting the Azure DevOps pipeline (_REDACTED URL_). Please reference '**3994b5c5018bcbe424598c21c85a90d8ddf23be9**' when requesting support.

The full error log (error.txt):
There was an error extracting the Azure DevOps pipeline (_REDACTED URL_)
Please reference 'REDACTED' when requesting support.
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/configuration.rb:303:in `call_validation_error_handler'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/props/private/setter_factory.rb:184:in `raise_pretty_error'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/props/private/setter_factory.rb:155:in `block in nilable_proc'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/props/constructor.rb:26:in `instance_exec'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/props/constructor.rb:26:in `block in construct_props_without_defaults'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/props/constructor.rb:23:in `each_pair'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/props/constructor.rb:23:in `construct_props_without_defaults'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/_methods.rb:277:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/props/weak_constructor.rb:14:in `initialize'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/_methods.rb:277:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/bundle/gems/actions_importer-1.2.18576/lib/valet/services/azure_devops/pipeline/extract_templates.rb:45:in `new'
/usr/local/bundle/gems/actions_importer-1.2.18576/lib/valet/services/azure_devops/pipeline/extract_templates.rb:45:in `call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
/usr/local/bundle/gems/actions_importer-1.2.18576/lib/valet/services/azure_devops/pipeline/extract_pipeline.rb:125:in `pipeline_attributes_from_client'
/usr/local/bundle/gems/actions_importer-1.2.18576/lib/valet/services/azure_devops/pipeline/extract_pipeline.rb:53:in `extract'
/usr/local/bundle/gems/actions_importer-1.2.18576/lib/valet/services/azure_devops/extract_all_pipelines.rb:38:in `block (2 levels) in build_pipelines'
/usr/local/bundle/gems/actions_importer-1.2.18576/lib/valet/models/thread_collection.rb:8:in `block in perform_later'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'

We have tried to run it twice - both with the same error.
Any idea what may be wrong? Otherwise I will migrate the rest manually.

**Comment by ethanis** [comment]
@FabianBigler sorry to hear you're running into this issue! Can you please open up a support ticket with GitHub support [here](https://support.github.com/) to get assistance? That way, we'll be able to triage this accordingly and have a space to share private pipeline details, if they are needed in order to remediate this.
