### ISSUE TITLE
Can make `travis-ci-organization` parameter optional?

### ISSUE THREAD

**Issue by Jeff-Tian** [github/gh-actions-importer#127]
My Travis ci repo: https://app.travis-ci.com/github/Jeff-Tian/id3
My Github repo: https://github.com/Jeff-Tian/id3

When trying to import, the following error occurs:

```
➜  id3 git:(master) ✗ gh actions-importer update
Updating ghcr.io/actions-importer/cli:latest...
ghcr.io/actions-importer/cli:latest up-to-date
➜  id3 git:(master) ✗ gh actions-importer migrate travis-ci --travis-ci-repository https://app.travis-ci.com/github/Jeff-Tian/id3 --output-dir .github --target-url https://github.com/Jeff-Tian/id3
[2023-05-05 12:01:34] No value provided for the required options '--travis-ci-organization'
[2023-05-05 12:01:34] Logs: './log/valet-20230505-120134.log'
```

So travis-ci-organization is required. But I don't have one. Do you know how I can bypass it?

<img width="1153" alt="image" src="https://github.com/github/gh-actions-importer/assets/3367820/3200e45b-c12f-4882-8fc6-75a1789c7c0e">

**Comment by Jeff-Tian** [comment]
By checking the source code, it is optional. However, if I don't provide a value, it raises error like the following:

```
➜  id3 git:(master) ✗ gh actions-importer migrate travis-ci --travis-ci-repository https://app.travis-ci.com/github/Jeff-Tian/id3 --output-dir .github --target-url https://github.com/Jeff-Tian/id3
[2023-05-06 01:31:33] No value provided for the required options '--travis-ci-organization'
[2023-05-06 01:31:33] Logs: './log/valet-20230506-013133.log'
```

**Comment by ethanis** [comment]
@Jeff-Tian the option is optional in the C# code because the value can also be provided by setting the `TRAVIS_CI_ORGANIZATION` environment variable. In your case, I think you'll just need to rework the `--travis-ci-repository` option to not be a fully qualified url. For example:

```bash
gh actions-importer migrate travis-ci --travis-ci-organization Jeff-Tian --travis-ci-repository id3 --output-dir .github --target-url https://github.com/Jeff-Tian/id3
```

**Comment by Jeff-Tian** [comment]
Thanks @ethanis !
