### ISSUE TITLE
Remove requirement for namespace in GitLab migrate/dry-run

### ISSUE THREAD

**Issue by vbui512** [github/gh-actions-importer#155]
The api of my gitlab repo does not require a namespace. Only the project ID is required to return the necessary information and adding the namespace results in a 404 Not Found error. Any way I can activate the dry-run/migrate commands without specifying the namespace? Otherwise please make changes allow the command to run and fetch without specifying namespace. Thanks!

Additional info:
Windows
gh version 2.29.0 (2023-05-10)
gh actions-importer     github/gh-actions-importer      v1.3.2
actions-importer/cli:latest     v1.3.19139

**Comment by Chaseshak** [comment]
Hi @vbui512!

What type of GitLab repo are you using?

If it's a personal repo, you should be able to use the username for the namespace argument. See [GitLab's documentation](https://docs.gitlab.com/ee/user/namespace/index.html#determine-which-type-of-namespace-youre-viewing) for more information on namespaces for different types of accounts.

For example, take my testing repo https://gitlab.com/Chaseshak/ci-testing (my username is `Chaseshak`):

```shell
gh actions-importer dry-run gtilab -o gitlab-test --namespace chaseshak --project ci-testing
```

Let me know if you're still having trouble.

**Comment by vbui512** [comment]
Hi @Chaseshak , I am using an enterprise instance of GitLab hosted by my university's server and we are trying to migrate to our GitHub Enterprise instance. The url for our gitlab api is formatted differently and does not work if I include a namespace. It also requires group ID and project ID instead of namespace and project name, but this is easily adaptable by passing in group ID instead of namespace and so on.

My gitlab repo is hosted at: https://csil-git1.cs.surrey.sfu.ca/415-hha_cbr/cbr-platform
For example, I successfully executed the "audit" command with this `gh actions-importer audit gitlab --output-dir tmp/audit --namespace 8795` but it would not work if I do this  `gh actions-importer audit gitlab --output-dir tmp/audit --namespace 415-hha_cbr`. That is because the api is reachable at https://csil-git1.cs.surrey.sfu.ca/8795.

For the dry-run and migrate commands, I need to reach: https://csil-git1.cs.surrey.sfu.ca/api/v4/projects/27454. (27454 is the project ID, passed in as the --project argument). The first part, https://csil-git1.cs.surrey.sfu.ca/api/v4/projects/, was formatted correctly in the program, as we are able to see this when the 404 returns: 
![image](https://github.com/github/gh-actions-importer/assets/132247121/20d322d4-6aca-4a57-a3c3-48c36471c1a2)

But adding the namespace argument causes the URL to become malformed (%2F instead of /) because the api is set up differently on our server. Even if it wasn't malformed, it wouldn't be reachable at https://csil-git1.cs.surrey.sfu.ca/api/v4/projects/8795/27454 because that is not where it is supposed to be. 

I just need to pass in the project ID and ignore the namespace for this command to successfully run. Please let me know what I can do.

**Comment by Chaseshak** [comment]
Thanks for the additional information. I'm having trouble reproducing your issue.

I have a few follow-up questions:

* What is the root URL of your API? Is `8795` part of the API root?
    * > That is because the api is reachable at https://csil-git1.cs.surrey.sfu.ca/8795
* What is the exact command you ran for the screenshot in your message above?
    * Can you share your log file for that run as well?

I believe the `%2F` instead of the `/` in this case is correct, as `%2F` is the URL encoding of the forward slash, which the [GitLab documentation asks for](https://docs.gitlab.com/ee/api/rest/index.html#namespaced-path-encoding).

I'm not sure how many pipelines you have to migrate, but you should also be able to migrate them one at a time locally by using the `--source-file-path` command. That still requires you to pass a `--namespace` and `--project`:

```shell
gh actions-importer dry-run gitlab --source-file-path path/to/your/pipeline.yml --project bar --namespace foo

[2023-05-31 19:00:23] Logs: 'gitlab/log/valet-20230531-190023.log'
[2023-05-31 19:00:23] Output file(s):
[2023-05-31 19:00:23]   gitlab/foo/bar/.github/workflows/bar.yml
```

**Comment by vbui512** [comment]
Thanks for all your help, I think I figured out a workaround.
