### ISSUE TITLE
[Support]: no newline included at end of failure output

### ISSUE THREAD

**Issue by jsoref** [github/gh-actions-importer#16]
### What operating system are you using?

- [ ] Linux
- [X] macOS
- [ ] Windows

### What version of the tool are you using?

```sh
% gh actions-importer version
gh version 2.20.2 (2022-11-15)
gh actions-importer	github/gh-actions-importer	v1.0.1
actions-importer/cli	unknown
```

### What happened?

There was no EOL at the end of the error message.

zsh inserts `%`+`\n` when the last line of output from a program doesn't include a newline.

The code appears to come from here:
https://github.com/search?q=%22image+prior+to+running+this+command%22+org%3Agithub&type=code

I can't tell if this is a bug in https://github.com/cli/cli or in this repository.

Either way, programs should include a newline, otherwise shells that aren't as helpful as zsh will just start writing their new prompt right after the output.

### Relevant log output

```shell
% gh actions-importer audit gitlab --output-dir ./output
Unable to locate GitHub Actions Importer image locally. Please run `gh actions-importer update` to fetch the latest image prior to running this command.%
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ethanis** [comment]
Thanks for opening this! This behavior will be corrected in the next release of this repo (likely Fri, Dec 2) 🎉
