### ISSUE TITLE
[Support]: The `#     #` for a failed transformer should have the proper yaml depth

### ISSUE THREAD

**Issue by jsoref** [github/gh-actions-importer#17]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
gh actions-importer	github/gh-actions-importer	v1.0.1
actions-importer/cli	v1.0.14396

### What happened?

https://github.com/actions/importer-labs/blob/173902d5bb22386408f0e4a0759ba31083d2d1c1/gitlab/5-custom-transformers.md?plain=1#L37-L51

### Relevant log output

```shell
jobs:
  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PLAN: plan.cache
      PLAN_JSON: plan.json
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 20
        lfs: true
    - run: terraform plan -out=$PLAN
    - run: terraform show --json $PLAN | convert_report > $PLAN_JSON
#     # 'artifacts.terraform' was not transformed because there is no suitable equivalent in GitHub Actions
```

I understand that yaml will ignore the line entirely and this won't actually result in a later job being treated as not a child of `jobs`, but there's no particularly good reason not to have the first `#` have an indentation that corresponds to its depth in the yaml tree -- it's a lot easier to reason through if it did.
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ethanis** [comment]
Thanks for opening this issue! The location of these comment markers is intentional so that commented out sections of yaml will be aligned correctly if they were to be uncommented via keyboard shortcuts (i.e command + /).
