### ISSUE TITLE
Add support for Azure Pipelines Terraform tasks

### ISSUE THREAD

**Issue by mike-equinox** [github/gh-actions-importer#19]
### What operating system are you using?

- [ ] Linux
- [ ] macOS
- [X] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
https://github.com/cli/cli/releases/tag/v2.20.2
gh actions-importer     github/gh-actions-importer      v1.0.1
gh ado2gh       github/gh-ado2gh        v0.30
gh valet        github/gh-valet v0.1.18
actions-importer/cli    v1.0.14403

### What happened?

Terraform are currently not supported. While these can be easily converted manually to using the Terraform CLI, this is time consuming given the number of pipelines in our projects.

https://github.com/microsoft/azure-pipelines-terraform/tree/main/Tasks/TerraformTask/TerraformTaskV3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mike-equinox** [comment]
Thanks, Ethan. This is fantastic! It gives us the flexibility to mould each migration to fit our requirements. Well done on designing this into the framework. And kudos for great documentation.

It so happens that the ADO TerraformTask is merely a wrapper around the terraform.exe cli tool, so writing a custom transformer should be (almost) trivial.

**Comment by ethanis** [comment]
@mike-equinox support for transforming the terraform tasks has now shipped natively in GitHub Actions Importer 🎉
