### ISSUE TITLE
Any gh actions-importer fails to run docker image

### ISSUE THREAD

**Issue by hsjankie** [github/gh-actions-importer#203]
Hi, whenever i try to do a dry-run or an audit or any actions-importer command that needs to run the docker image it fails:

gh actions-importer audit jenkins -o .
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

What am I missing?

Thanks
Stefan

**Comment by Chaseshak** [comment]
Hi @hsjankie!

In order to better assist you, can you run `gh actions-importer update` to ensure you have the latest version?

After that, can you please reply with the following information:
* The output of `gh actions-importer version`
* The output of `docker version`
* What OS and version are you using?

**Comment by Chaseshak** [comment]
@hsjankie Thanks for the info!

I'm having trouble replicating your issue. However, it does seem like you're using an older (~2 years) version of Docker/Docker Engine. Are you able to install a newer version of Docker?

Also, are you using WSL or running this directly on Windows cmd prompt or power shell?

One more thing I can think of is have you configured your gh actions importer CLI? That could possibly cause this error https://docs.github.com/en/actions/migrating-to-github-actions/automated-migrations/automating-migration-with-github-actions-importer#authenticating-at-the-command-line

**Comment by hsjankie** [comment]
Thanks @Chaseshak ,

Upgraded and still got the same.
Running directly from the windows cmd prompt.

Initially ran the docker command with:

docker run --rm -t --network=host --env-file .env.local -v "X:\":/data ghcr.io/actions-importer/cli:latest audit jenkins -o .
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image


But this worked:

docker run --rm -t --network=host --env-file .env.local -v X:/:/data ghcr.io/actions-importer/cli:latest audit jenkins -o .
[2023-07-14 16:40:20] Logs: './log/valet-20230714-164020.log'

Seem it might have to do with the windows path?
Also seems to work with %cd%

**Comment by hsjankie** [comment]
Thanks, running it via "gh actions-importer audit jenkins -o ." I get:

[2023-07-14 17:26:58] Logs: './log/valet-20230714-172658.log'
[2023-07-14 17:26:58] Auditing 'https://*****/jenkins'
[2023-07-14 17:26:59] Failed to connect to 'https://*****/jenkins/api/json?tree=jobs%5Bname%2Curl%2CfullName%5D'. Please ensure the server is reachable and your environment variables and options are set correctly. Error: 503 "Service Unavailable"

But running it directly with the docker command still seems to work, strange...

**Comment by Chaseshak** [comment]
Did you re-configure the CLI after you moved to the new directory? The credentials that you input during `gh actions-importer configure` are saved to the file `.env.local`, so likely that file is still in your root drive! You can either copy it to the new folder or run the configure command again!

**Comment by Chaseshak** [comment]
I believe we've solved your original issue. If you're having anymore trouble, please let us know!

**Comment by hsjankie** [comment]
@Chaseshak Thanks for the help with this
