### ISSUE TITLE
404 Not found when trying to audit an Azure Devops project

### ISSUE THREAD

**Issue by Logikgate** [github/gh-actions-importer#227]
Hello,

I am getting the below error when trying to audit the pipelines of my Azure DevOps project. 

It seems that the url it is trying to reach is not correct. https://[org].visualstudio.com/[org]/[project] is what it is using but the actual url is https://[org].visualstudio.com/[project].  I.e. without the org in the url path it works.  

Is there something I can do to fix the url template?

There was an error extracting pipelines from Azure DevOps 
                      Message: Resource not found
                      (GET 404) Not Found: https://[org].visualstudio.com/[org]/[project]/_apis/build/definitions?api-version=5.0&includeAllProperties=true&queryOrder=lastModifiedDescending

**Comment by begonaguereca** [comment]
Hi @Logikgate! So sorry to hear that you've been experiencing some troubles. In this scenario I am going to ask that you please open up a support ticket [here](https://support.github.com/) 🙏🏽

**Comment by Logikgate** [comment]
No problem, I have opened a support ticket there
