### ISSUE TITLE
[Support]: Output directory for operations is owned by root.

### ISSUE THREAD

**Issue by akb825** [github/gh-actions-importer#23]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
gh actions-importer     github/gh-actions-importer      v1.0
actions-importer/cli    v1.0.14451

### What happened?

When running commands that take an output directory (with azure-devops in my case), the output directory is owned by root. Ideally the UID and GID would be forwarded to Docker to ensure that the output is owned by the current user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chaseshak** [comment]
Hi @akb825!

We're looking into this on our end.

To make sure that we correctly replicate your issue, can you please share a few more details:
1. What Linux distribution and version are you using (`cat /etc/os-release`)?
2. Are you still able to read and write the files in the output directory even though they are owned by the root user?
3. Can you share the result of `ls -alh path/to/your/output`?

**Comment by akb825** [comment]
Hi, to answer your questions:
1. I'm using Arch Linux. It is a rolling distribution, so there's no direct version number.
2. I can still read files in the output directory, but writing can't be done without root access. (e.g. `sudo` or changing to root with `su`)
3. This is the output from running `ls -alh`:
    ```
    drwxr-xr-x  4 root    root  4.0K Dec  1 23:21 .
    drwxr-xr-x 50 abarany users 4.0K Jan 24 20:46 ..
    drwxr-xr-x  2 root    root  4.0K Dec  3 22:27 log
    drwxr-xr-x  3 root    root  4.0K Dec  1 23:21 pipelines
    ```
    As you can see, the owner and group of the contents are both root.

**Comment by pashcan** [comment]
Seeing the same issue with the following importer version
```
$ gh actions-importer version
gh version 2.21.2 (2023-01-03)
gh actions-importer	github/gh-actions-importer	v1.2.1
actions-importer/cli:latest	v1.2.17997
```
And this output for `cat /etc/os-release`:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
It is also failing to create the actual converted files other than the log directory despite listing the Output files section and "generated" file paths in the log.

This is the `ls -alh` output:
```
$ ls -alh         
total 12K
drwxr-xr-x 3 root root 4.0K Apr 14 19:04 .
drwxr-xr-x 3 root root 4.0K Apr 14 19:04 ..
drwxr-xr-x 2 root root 4.0K Apr 14 19:04 log
```
