### ISSUE TITLE
[Support]: Conversion of azure-devops PublishTestResults@2 uses very old version of publish-unit-test-result-action and doesn't execute

### ISSUE THREAD

**Issue by akb825** [github/gh-actions-importer#26]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
gh actions-importer     github/gh-actions-importer      v1.0
actions-importer/cli    v1.0.14451

### What happened?

Jobs that use PublishTestResults@2 for azure-devops end up being converted to `EnricoMi/publish-unit-test-result-action@v1.7`. This is quite old, and I would expect it to target `EnricoMi/publish-unit-test-result-action@v1` when targeting the version 1 branch, which is currently at v1.40. The version 2 branch is also available, though it does have breaking changes.

The converted job additionally doesn't execute, complaining that `GITHUB_TOKEN` isn't set. I'm not sure if this is due to using the very old version or if the v1 branch requires additional options. When updating the jobs to v2 I didn't need to add any extra options to utilize the builtin pipeline token.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ethanis** [comment]
@akb825 thanks for opening this issue! We regularly audit the versions of actions that are used by GitHub Actions Importer and will be updating this version shortly 🙌

**Comment by j-dunham** [comment]
`EnricoMi/publish-unit-test-result-action` now at latest version
