### ISSUE TITLE
[Support]: checkout and upload-artifact actions use v2, which warn about usage of Node 12

### ISSUE THREAD

**Issue by akb825** [github/gh-actions-importer#27]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
gh actions-importer     github/gh-actions-importer      v1.0
actions-importer/cli    v1.0.14451

### What happened?

When converting my pipelines from azure-devops, the checkout and upload-artifact options use `v2`, which use Node 12. This causes the following warnings to be output when running the pipelines:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

Switching these actions to v3, which use Node 16, silenced the warnings.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by j-dunham** [comment]
Hi @akb825 thanks for the issue! Those actions have been updated and are used in the latest version.  To get the latest version run `gh actions-importer update`
