### ISSUE TITLE
Document product feedback loops

### ISSUE THREAD

**Issue by andyfeller** [github/gh-actions-importer#29]
# Overview

With the public beta of GitHub Actions Importer, it is important to capture and direct adopters to appropriate feedback loops for discussion and product feedback.  This issue is a follow up from internal discussions to document current feedback loops:

### External / Direct User Feedback 
1. [Community discussions board](https://github.com/github/gh-actions-importer/discussions/categories/feature-ideas-and-feedback) - Hosted directly in the Actions Importer Repo and serves as the main destination for user feedback. 
1. Open discussions on the [Actions and Packages section](https://github.com/orgs/community/discussions/categories/actions-and-packages) of the overall [GitHub Community discussions](https://github.com/orgs/community/discussions)

### Internal Feedback Collection
1. [Internal Feedback Form](https://github.com/github/customer-feedback/issues/new?assignees=&labels=Compute+Products&template=03-compute-products.yml&title=%3CTitle%3E) - Mainly for CS, CSAs and Support Eng to share customer feedback with the team.
1. [Feedback board ](https://github.com/orgs/github/projects/8654/views/13)- Feedback submitted from internal folks using the internal feedback form tracked in this view
1. Open issues on https://github.com/github/gh-actions-importer/issues

**Comment by dawita66** [comment]
Updated the issue to include all feedback tracking paths we currently have in place.

**Comment by dawita66** [comment]
@ethanis @andyfeller please review when you get a chance and let me know if you have any feedback. Thanks!

**Comment by ethanis** [comment]
Looks good! We'll be updating the public facing documentation in #46 to point people to use discussions for feedback/ideas
