### ISSUE TITLE
Internal error while transforming the Azure pipelines

### ISSUE THREAD

**Issue by KalpanaReddyC** [github/gh-actions-importer#35]
### What operating system are you using?

- [ ] Linux
- [ ] macOS
- [X] Windows

### What version of the tool are you using?

![image](https://user-images.githubusercontent.com/33893559/211593432-f3736fb1-4ac4-44ae-b43a-328856a8c5f0.png)

### What happened?

[Support]: There was an internal error transforming the Azure DevOps pipeline (NewTBS) into a GitHub Actions workflow. Please reference 'ac5297a8ce4222d44dab8c2f8717c55ae318b52c' when requesting support.

There was an internal error transforming the Azure DevOps pipeline (NewTBS) into a GitHub Actions workflow. Please reference '8dc6337155ec0c22cf6d37d9b4623daf2f8c4bf0' when requesting support.

### Relevant log output

```shell
PS C:\Users\Kalpana Reddy> gh actions-importer migrate azure-devops pipeline -u https://dev.azure.com/infomagnus/NewTBS/_apis/build/definitions?api-version=5.0 --target-url https://github.com/im-sandbox-kalpanarc/MigrationTarget --output-dir .
[2023-01-10 15:34:16] Logs: './log/valet-20230110-153416.log'
[2023-01-10 15:34:18] There was an internal error transforming the Azure DevOps pipeline (NewTBS) into a GitHub Actions workflow.
                      Please reference '8dc6337155ec0c22cf6d37d9b4623daf2f8c4bf0' when requesting support.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by j-dunham** [comment]
Hi @KalpanaReddyC sorry for the delay.  Can you please do the following
- Update GitHub Actions Importer by running `gh actions-importer update`
- Run this edited version of the command you provided with `PIPELINE_ID` updated with the pipeline id.  The command you provided was missing this.
```command
gh actions-importer migrate azure-devops pipeline -u "https://dev.azure.com" --target-url https://github.com/im-sandbox-kalpanarc/MigrationTarget --output-dir . --pipeline-id PIPELINE_ID
```

If the command still fails please provide the Pipeline yaml so we can investigate further.  Makesure to remove any sensitive information in the pipeline.

**Comment by ethanis** [comment]
Marking this as stale. Please open a [support ticket](https://support.github.com) if you continue to run into this.
