### ISSUE TITLE
Support for GoCD

### ISSUE THREAD

**Issue by sergiofigueras** [github/gh-actions-importer#36]
Hello there folks,

I just would like to know if there is any support for GoCD planned at all. If not, would the development accept help to develop an importer for GoCD?

Thanks.

**Comment by ethanis** [comment]
@sergiofigueras at this time, we don't have any plans on our roadmap to support GoCD migrations. This repository containing the CLI frontend is open source, however, the majority of the code that powers a migration remains private and we're not accepting outside contributions there.
