### ISSUE TITLE
[Support]: Unable to locate credentials for 'https://github.com'

### ISSUE THREAD

**Issue by volatilemolotov** [github/gh-actions-importer#37]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.21.2 (2023-01-04)
gh actions-importer     github/gh-actions-importer      v1.0.2
actions-importer/cli    v1.0.15569

### What happened?

Trying a dry run for jenkins, get the following output:
```
Unable to locate credentials for 'https://github.com'
```
Problem is understanding what credentials it expects and where to put them. CLI logged in already

### Relevant log output

```shell
# Logfile created on 2023-01-25 13:43:42 +0000 by logger.rb/v1.4.2
I, [2023-01-25T13:43:42.213440 #1]  INFO -- : Using GitHub Features: 'all'
E, [2023-01-25T13:43:42.213463 #1] ERROR -- : Unable to locate credentials for 'https://github.com'
/usr/local/bundle/gems/actions_importer-1.0.15569/lib/valet/models/credentials_store.rb:79:in `credentials_for_url'
/usr/local/bundle/gems/actions_importer-1.0.15569/lib/valet/models/credentials_store.rb:63:in `block in parse_credentials'
/usr/local/bundle/gems/actions_importer-1.0.15569/lib/valet/models/credentials_store.rb:59:in `each'
/usr/local/bundle/gems/actions_importer-1.0.15569/lib/valet/models/credentials_store.rb:59:in `parse_credentials'
/usr/local/bundle/gems/actions_importer-1.0.15569/lib/valet/concerns/cli_utilities.rb:65:in `fill_valet_options'
/usr/local/bundle/gems/actions_importer-1.0.15569/lib/valet/subcommands/dry_run.rb:27:in `jenkins'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/actions_importer-1.0.15569/exe/actions-importer:16:in `<top (required)>'
/usr/local/bundle/bin/actions-importer:23:in `load'
/usr/local/bundle/bin/actions-importer:23:in `<main>'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ethanis** [comment]
@volatilemolotov the best way to configure the credentials needed is to run the `gh actions-importer configure` command to start an interactive prompt to set the credentials needed. This command will output a `.env.local` file in your working directory that stores these values.

In this case, it looks like there is a missing env variable named `GITHUB_ACCESS_TOKEN` that should be set to the GitHub PAT that will be used to fetch Jenkinsfile contents stored in GitHub and to open pull requests up on your behalf (via the `migrate` command)

**Comment by volatilemolotov** [comment]
It looks like issue was that i was trying to use `GITHUB_TOKEN` instead of `GITHUB_ACCESS_TOKEN`. Confusion comes from `gh` cli tool which uses `GITHUB_TOKEN` and i was able to install actions-importer tool and run the `update` command so it made me think that the issue is elsewhere. 

Perhaps there is value on making the ENV var used named the same? 


Thanks for help

**Comment by ethanis** [comment]
Closing this as a token is no longer required to run the `update` command 🎉
