### ISSUE TITLE
[Support]: Gitlab migration CI_PROJECT_NAMESPACE not recognized

### ISSUE THREAD

**Issue by Daniel-Klockenkaemper** [github/gh-actions-importer#7]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

Latest Beta

### What happened?

When migrating a Gitlab CI configuration the Gitlab environment variable "`$CI_PROJECT_NAMESPACE`" will be replace by `${{ github.event.repository.name }}SPACE`. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by j-dunham** [comment]
Hi @Daniel-Klockenkaemper  I found the issue for the addition of `SPACE` on the end but wanted to confirm that was the issue  you had with `${{ github.event.repository.name }}SPACE`

**Comment by j-dunham** [comment]
Hi @Daniel-Klockenkaemper  I have deployed the fix.   Please do `gh actions-importer update` and retry.  You now should just get `${{ github.repository_owner }}` instead of `${{ github.event.repository.name }}SPACE`

Please reopen if you expected a different result

**Comment by Daniel-Klockenkaemper** [comment]
Thank you very much, it works now!
