### ISSUE TITLE
Bitbucket Server URL pattern not matching

### ISSUE THREAD

**Issue by chrissike** [github/gh-actions-importer#79]
Hi owners,

I'm facing an issue with the expected format for the Bitbucket server URLs.

This is the error message I get when running the audit command:

Message: There was an error retrieving file contents from Bitbucket ()
Message: Unable to parse Bitbucket repository URL. Ensure it is in the format of https://bitbucket.company.com/projects/:project_name/repos/:repo_name
Bitbucket URL provided: https://bitbucket.company.com/bitbucket/scm/project/repo.git

The only case where I've seen this expected ".../projects" URL pattern is when browsing the UI, it's never used in any connectivity configuration.

We're using Bitbucket Server v7.17.13, Jenkins 2.346.3, Bitbucket Branch Source plugin for Jenkins Version 773.v4b_9b_005b_562b_

Would it be possible to adjust the expected URL pattern or also allow for this one? That would be of great help as otherwise we can't use the actions importer.
BR Christina

**Comment by simonsanchez** [comment]
Thanks for the feedback! This issue has been fixed in the latest release. 

You can update to it with `gh actions-importer update`
