### ISSUE TITLE
Failed to Run Extension - Error

### ISSUE THREAD

**Issue by ecampamavens** [github/gh-actions-importer#98]
I downloaded gh actions-importer using the following command:

`gh extension install github/gh-actions-importer
Cloning into '/Users/admin/.local/share/gh/extensions/gh-actions-importer'...
remote: Enumerating objects: 2136, done.
remote: Counting objects: 100% (792/792), done.
remote: Compressing objects: 100% (505/505), done.
remote: Total 2136 (delta 319), reused 690 (delta 282), pack-reused 1344
Receiving objects: 100% (2136/2136), 492.93 KiB | 683.00 KiB/s, done.
Resolving deltas: 100% (1157/1157), done.
`
The output shows clearly it was able to download the extension. When I proceed to run the command:
`gh actions-importer update                     
failed to run extension: fork/exec /Users/admin/.local/share/gh/extensions/gh-actions-importer/gh-actions-importer: no such file or directory%`

I get the above error. I verified that the path `/gh-actions-importer/gh-actions-importer` does not exist.

**Comment by begonaguereca** [comment]
Hi @ecampamavens sorry to hear you are running into problems. Could you run the following command and let me know what the output is? 

`ls --tree /Users/admin/.local/share/gh/extensions`

Thank you!

**Comment by ecampamavens** [comment]
I am using MacOS so no `tree` command available.

gh version 2.0.0 (2021-08-23)
https://github.com/cli/cli/releases/tag/v2.0.0

Darwin x86_64


I tried the below command which uninstalls then installs again but still get the same behavior.
`gh extension remove actions-importer && gh extension install github/gh-actions-importer
`

**Comment by begonaguereca** [comment]
Hmm lets try updating the version of the CLI that version might have been before we added the extension. How did you install it? Heres some docs to help you run the correct update command: 

https://github.com/cli/cli

**Comment by ecampamavens** [comment]
Seems like updating homebrew did the trick, I was running an unsupported version of MacOS.
